project: 
  type: website

website: 
  title: CogPlatform
  favicon: img/look.png

  navbar:
    left:
      - href: index.qmd
        text: Home

  sidebar: 
    search: true
    style: floating
    contents: 
      - section: "Start with PTB"
        contents: src/PTB/*
      - section: "Equipment"
        contents: src/equipment/*
      - section: "Pipelines"
        contents:
          - src/Pipelines.qmd
      - section: "Tools"
        contents:
          - src/GITHUB.qmd