project: 
  type: website
format:
  html:
    theme:
      light: lux
      dark: darkly
website: 
  title: Cognitive & Behavioural Research Platform, CAS
  favicon: img/look.png
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  other-links: "https://github.com/CogPlatform/Notes"
  navbar:
    logo: img/logo1.png
    right:
      - href: index.qmd
        text: Home
  sidebar: 
    search: true
    style: floating
    tools:
      - icon: github
        href: https://github.com/
    contents: 
      - section: "Start with PTB"
        contents: src/PTB/*
      - section: "Equipment"
        contents: src/equipment/*
      - section: "Pipelines"
        contents:
          - src/Pipelines.qmd
      - section: "Tools"
        contents:
          - src/GITHUB.qmd
